### ISSUE TITLE
Since v5 returned data is always undefined at first request

### ISSUE THREAD

**Issue by Petar-I-Ivanov** [tronikelis/solid-swr#62]
Heres the request:
![image](https://github.com/user-attachments/assets/b8080014-611f-429e-ac35-237099cecf81)
and previews undefined:
![image](https://github.com/user-attachments/assets/dfca1ee3-ddcc-4182-a4f3-f65565543a12)

After refetching:
![image](https://github.com/user-attachments/assets/e6cc7034-cc90-4474-b533-daf9827ac9a0)
previewed data is correct:
![image](https://github.com/user-attachments/assets/5f38db14-0935-4dae-bb3f-7b4d5c7fe70e)

Here's the usage:
![image](https://github.com/user-attachments/assets/807758ac-b580-4b6b-a240-5aa7e958b545)
and
![image](https://github.com/user-attachments/assets/9f01c1b7-5cc6-4587-9858-8f9abb24ddb9)

At v4.1.0 it is configured and used the same way but returns correct data on the first request

**Comment by tronikelis** [comment]
> I'm dumb, descructing v() was causing the issue

Happens to me sometimes as well :DD, you can think of `v()` as `store[key]` because that is literally what it is, so you have to call it in a reactive context, and destructuring called it implicitly

https://github.com/tronikelis/solid-swr/blob/bcaa19a58efd4fb06cd35efb64a5923d9cbc1ccd/src/core.ts#L192
